env: false

pagehelper:
  reasonable: false
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

spring:
  redis:
    redisson:
      config: classpath:redisson.yaml
  jackson:
      serialization:
        write-dates-as-timestamps: true
      default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/test_tmp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  transaction:
    rollback-on-commit-failure: true

log:
  server:
    path: ../logs/console

logging:
  level:
    org:
      springframework:
        boot: debug
        web: debug
        jdbc: debug
        dao: debug
        transaction: debug
      mybatis: debug
    com:
      github:
        fartherp: debug

shiro:
  annotations:
    enabled: true
  web:
    enabled: true

info:
  blog-url: http://127.0.0.1:8080
  author: CK
  version: 1.0.0